export enum EndpointEnum {
  AWESOME_SINK_EXPLORATION = "getExplorationSink",
  AWESOME_SINK_RESOURCE = "getResourceSink",
  BIOMASS_GENERATOR = "getBiomassGenerator",
  COAL_GENERATOR = "getCoalGenerator",
  DRONE = "getDrone",
  DRONE_STATION = "getDroneStation",
  FUEL_GENERATOR = "getFuelGenerator",
  GEOTHERMAL_GENERATOR = "getGeothermalGenerator",
  NUCLEAR_GENERATOR = "getNuclearGenerator",
  PLAYER = "getPlayer",
  POWER = "getPower",
  TRAIN = "getTrains",
  TRAIN_STATION = "getTrainStation",
  VEHICLE = "getVehicles",
  WORLD_INV = "getWorldInv",
}
